import { serverTimestamp } from 'firebase/firestore'
import { format, startOfWeek, differenceInCalendarWeeks } from 'date-fns'

/**
 * Regras de Domínio para Sessões (Aulas individuais) e Planejamento
 */
export const SessionRules = {
    /**
     * Payload para atualização manual de uma sessão
     */
    buildUpdatePayload: (userId, data) => {
        return {
            ...data,
            updatedBy: userId,
            updatedAt: serverTimestamp()
        };
    },

    /**
     * Payload para cancelamento de uma sessão específica
     */
    buildCancelPayload: (userId, reason = '') => {
        return {
            status: 'canceled',
            canceledAt: serverTimestamp(),
            canceledBy: userId,
            cancellationReason: reason,
            updatedBy: userId,
            updatedAt: serverTimestamp()
        };
    },

    /**
     * Payload para criação de um novo planejamento (manual)
     */
    buildPlanningPayload: (userId, planningData) => {
        return {
            ...planningData,
            status: 'active',
            createdAt: serverTimestamp(),
            createdBy: userId
        };
    },

    /**
     * Calcula o planejamento automático para uma sessão baseado na sequência gerada
     */
    calculateAutoPlanning: (userId, session, firstSessionDate, planSequence, currentWeekState) => {
        const dateObj = new Date(session.sessionDate + 'T12:00:00');

        // Identificar semana da sessão para pegar o conjunto correto da sequência
        const weekIndex = Math.abs(differenceInCalendarWeeks(dateObj, firstSessionDate));
        const safeSequenceIndex = weekIndex % planSequence.length;
        const weekObjectives = planSequence[safeSequenceIndex] || [];

        if (weekObjectives.length === 0) return null;

        // Lógica de Foco Semanal vs Herança
        const weekStartStr = format(startOfWeek(dateObj, { weekStartsOn: 1 }), 'yyyy-MM-dd');
        let isFocus = false;
        let inheritedFrom = null;

        if (weekStartStr !== currentWeekState.weekStart) {
            // Nova semana -> Define novo foco
            currentWeekState.weekStart = weekStartStr;
            currentWeekState.focusSessionId = session.id;
            isFocus = true;
        } else {
            // Mesma semana -> Herda do foco anterior
            isFocus = false;
            inheritedFrom = currentWeekState.focusSessionId;
        }

        return {
            objectives: weekObjectives,
            weekId: `${format(dateObj, 'yyyy')}-W${format(dateObj, 'w')}`,
            isWeeklyFocus: isFocus,
            inheritedFromSessionId: inheritedFrom,
            status: 'active',
            autoGenerated: true,
            createdAt: serverTimestamp(),
            createdBy: userId || 'system',
            weekSequenceIndex: weekIndex
        };
    },

    /**
     * Calcula o número de semanas necessárias para a sequência de planejamento
     */
    calculatePlanningWeeksCount: (startDateString, lastSessionDateString) => {
        const start = new Date(startDateString);
        const end = new Date(lastSessionDateString);
        return Math.abs(differenceInCalendarWeeks(end, start)) + 4; // +4 de margem de segurança
    }
};
