export const CRM_CLIENTS = [
    {
        id: "c1",
        name: "Mariana Souza",
        photo: "https://via.placeholder.com/96x96.png?text=MS",
        segments: ["birthday", "active", "credit"],
        statusLabel: "Ativa",
        statusColor: "success",
        referenceDate: "2026-05-12",
        referenceLabel: "Aniversário em 12/05",
        email: "mariana.souza@example.com",
        phone: "(11) 98888-1001",
        segmentInfo: "Aniversário: 12/05 · Ativa",
        contract: "Plano anual · vence 02/2027",
        balance: "Crédito de R$ 150,00",
        notes: "Prefere contato por WhatsApp à tarde.",
    },
    {
        id: "c2",
        name: "Diego Martins",
        photo: "https://via.placeholder.com/96x96.png?text=DM",
        segments: ["active", "contractsDue", "pending"],
        statusLabel: "Ativo",
        statusColor: "success",
        referenceDate: "2026-05-30",
        referenceLabel: "Contrato vence em 30/05",
        email: "diego.martins@example.com",
        phone: "(21) 99911-2233",
        segmentInfo: "Contrato prestes a vencer",
        contract: "Plano trimestral · vence 30/05",
        balance: "Saldo a confirmar",
        notes: "Quer migrar para o plano semestral.",
    },
    {
        id: "c3",
        name: "Letícia Carvalho",
        photo: "https://via.placeholder.com/96x96.png?text=LC",
        segments: ["suspended", "pending"],
        statusLabel: "Suspenso",
        statusColor: "warning",
        referenceDate: "2026-05-18",
        referenceLabel: "Suspenso desde 18/05",
        email: "leticia.carvalho@example.com",
        phone: "(31) 97777-8899",
        segmentInfo: "Suspensão temporária",
        contract: "Plano mensal · suspenso",
        balance: "Sem pendências",
        notes: "Retorna em junho; confirmar reativação.",
    },
    {
        id: "c4",
        name: "Rafael Lima",
        photo: "https://via.placeholder.com/96x96.png?text=RL",
        segments: ["canceled", "debt"],
        statusLabel: "Cancelado",
        statusColor: "danger",
        referenceDate: "2026-04-28",
        referenceLabel: "Cancelado em 28/04",
        email: "rafael.lima@example.com",
        phone: "(41) 96666-7788",
        segmentInfo: "Cancelado com saldo em aberto",
        contract: "Contrato cancelado",
        balance: "Saldo devedor R$ 230,00",
        notes: "Solicitou segunda via de boleto.",
    },
    {
        id: "c5",
        name: "Juliana Prado",
        photo: "https://via.placeholder.com/96x96.png?text=JP",
        segments: ["inactive"],
        statusLabel: "Inativo",
        statusColor: "secondary",
        referenceDate: "2026-03-10",
        referenceLabel: "Inativo desde 10/03",
        email: "juliana.prado@example.com",
        phone: "(11) 95555-6677",
        segmentInfo: "Avaliar campanha de reativação",
        contract: "Sem contrato ativo",
        balance: "Sem débitos",
        notes: "Costumava treinar às segundas.",
    },
    {
        id: "c6",
        name: "Carlos Andrade",
        photo: "https://via.placeholder.com/96x96.png?text=CA",
        segments: ["credit", "active"],
        statusLabel: "Ativo",
        statusColor: "success",
        referenceDate: "2026-06-05",
        referenceLabel: "Crédito expira em 05/06",
        email: "carlos.andrade@example.com",
        phone: "(85) 98888-0000",
        segmentInfo: "Possui crédito em aberto",
        contract: "Plano trimestral · vence 08/07",
        balance: "Crédito de R$ 90,00",
        notes: "Interessa em personal de natação.",
    },
    {
        id: "c7",
        name: "Fernanda Dias",
        photo: "https://via.placeholder.com/96x96.png?text=FD",
        segments: ["debt", "pending"],
        statusLabel: "Em atraso",
        statusColor: "danger",
        referenceDate: "2026-05-08",
        referenceLabel: "Vencimento 08/05",
        email: "fernanda.dias@example.com",
        phone: "(31) 96565-4545",
        segmentInfo: "Boleto vencido há 7 dias",
        contract: "Plano mensal · vence 08/06",
        balance: "Saldo devedor R$ 145,00",
        notes: "Cobrar atualização de pagamento.",
    },
]
