import { SessionRules } from '../SessionRules';
import { differenceInCalendarWeeks, startOfWeek, format } from 'date-fns';

// Mocks
jest.mock('firebase/firestore', () => ({
    serverTimestamp: () => 'MOCKED_TIMESTAMP'
}));

describe('SessionRules', () => {

    describe('buildUpdatePayload', () => {
        it('deve retornar o payload contendo updatedBy e updatedAt', () => {
            const data = { observations: 'Nova observação' };
            const payload = SessionRules.buildUpdatePayload('user-123', data);

            expect(payload.observations).toBe('Nova observação');
            expect(payload.updatedBy).toBe('user-123');
            expect(payload.updatedAt).toBe('MOCKED_TIMESTAMP');
        });
    });

    describe('buildCancelPayload', () => {
        it('deve retornar o payload de cancelamento com status e razao', () => {
            const payload = SessionRules.buildCancelPayload('user-456', 'Pneu furou');

            expect(payload.status).toBe('canceled');
            expect(payload.canceledBy).toBe('user-456');
            expect(payload.cancellationReason).toBe('Pneu furou');
            expect(payload.canceledAt).toBe('MOCKED_TIMESTAMP');
            expect(payload.updatedAt).toBe('MOCKED_TIMESTAMP');
        });

        it('deve usar string vazia caso a razão nao seja provida', () => {
            const payload = SessionRules.buildCancelPayload('user-456');
            expect(payload.cancellationReason).toBe('');
        });
    });

    describe('buildPlanningPayload', () => {
        it('deve construir o payload padrao de start do planning', () => {
            const planningData = { theme: 'Jiu Jitsu' };
            const payload = SessionRules.buildPlanningPayload('user-789', planningData);

            expect(payload.theme).toBe('Jiu Jitsu');
            expect(payload.status).toBe('active');
            expect(payload.createdBy).toBe('user-789');
            expect(payload.createdAt).toBe('MOCKED_TIMESTAMP');
        });
    });

    describe('calculateAutoPlanning', () => {
        const firstSessionDate = new Date('2025-01-01T12:00:00');
        const planSequence = [
            [{ id: 'obj1' }], // Semana 0
            [{ id: 'obj2' }]  // Semana 1
        ];

        it('deve retornar nulo se a sequencia estiver vazia', () => {
            const result = SessionRules.calculateAutoPlanning('user', { sessionDate: '2025-01-01' }, firstSessionDate, [], {});
            expect(result).toBeNull();
        });

        it('deve gerar plano e definir isFocus=true para a primeira sessão de uma nova semana', () => {
            const currentWeekState = { weekStart: null, focusSessionId: null };
            const session = { id: 'session-100', sessionDate: '2025-01-01' }; // Quarta-feira, Semana 0

            const result = SessionRules.calculateAutoPlanning('user-1', session, firstSessionDate, planSequence, currentWeekState);

            expect(result.objectives).toEqual([{ id: 'obj1' }]);
            expect(result.isWeeklyFocus).toBe(true);
            expect(result.inheritedFromSessionId).toBeNull();
            expect(result.status).toBe('active');
            expect(result.autoGenerated).toBe(true);

            // O state eh mutável e deve ser atualizado
            expect(currentWeekState.focusSessionId).toBe('session-100');
            expect(currentWeekState.weekStart).not.toBeNull();
        });

        it('deve herdar o foco da sessão anterior caso caia na mesma semana', () => {
            // Sessão na MESMA SEMANA da primeira
            const currentWeekState = {
                weekStart: format(startOfWeek(new Date('2025-01-01T12:00:00'), { weekStartsOn: 1 }), 'yyyy-MM-dd'),
                focusSessionId: 'session-100'
            };

            const session2 = { id: 'session-200', sessionDate: '2025-01-03' }; // Sexta-feira, mesma semana

            const result = SessionRules.calculateAutoPlanning('user-1', session2, firstSessionDate, planSequence, currentWeekState);

            expect(result.objectives).toEqual([{ id: 'obj1' }]);
            expect(result.isWeeklyFocus).toBe(false);
            expect(result.inheritedFromSessionId).toBe('session-100');
            expect(result.weekSequenceIndex).toBe(0);
        });

        it('deve pular sequencia caso o array de plano acabe (loop circular)', () => {
            const currentWeekState = { weekStart: null, focusSessionId: null };
            // Diferenca deve dar 2 semanas -> Week 2
            const session = { id: 'session-3', sessionDate: '2025-01-15' }; // Quarta-feira, 2 semanas depois

            // planSequence length is 2 (0, 1). Math abs 2 % 2 = 0 (loop in the array)
            const result = SessionRules.calculateAutoPlanning('user-1', session, firstSessionDate, planSequence, currentWeekState);

            expect(result.objectives).toEqual([{ id: 'obj1' }]); // Pegou do index 0 (circular)
            expect(result.weekSequenceIndex).toBe(2);
        });
    });

    describe('calculatePlanningWeeksCount', () => {
        it('deve calcular a diferenca em semanas + 4 margens', () => {
            const count = SessionRules.calculatePlanningWeeksCount('2025-01-01', '2025-01-15');
            // Diferenca é de 2 semanas, + 4 = 6
            expect(count).toBe(6);
        });
    });
});
